lsi: false
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-paginate
permalink: "/articles/:categories/:title.html"
paginate: 5
paginate_path: "/news/page:num/"
titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false
collections_dir: articles
collections:
  release-notes:
    output: true
  migration-guides:
    output: true
news_posts_max: 3
exclude:
  - build.sh
  - deploy.key
  - deploy.key.enc
